/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_crm_bsdiff_PatchUtils
#define _Included_com_crm_bsdiff_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crm_bsdiff_PatchUtils
 * Method:    genNewApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_bsdiff_PatchUtils_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
